### ISSUE TITLE
Adjusting the ASTM E 1049-85 Python Rainflow to 4 point 

### ISSUE THREAD

**Issue by karabobright71** [a-ma72/rainflow#1]
Python uses ASTM E 1049-85 3 Point Rainflow Count while glyphworks uses the 4 point method, Is there a way to adjust the 3 Point to 4 Point in Python?

Is there a 4 Point Rainflow code in Python?

**Comment by a-ma72** [comment]
This project offers a python package with ASTM E 1049 (2011) 4 point method now.
